### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by kun-dragon** [akshitac8/OW-DETR#10]
When I execute 'python test.py', I meet the problem

* True check_forward_equal_with_pytorch_double: max_abs_err 8.67e-19 max_rel_err 2.35e-16
* True check_forward_equal_with_pytorch_float: max_abs_err 4.66e-10 max_rel_err 1.13e-07
* True check_gradient_numerical(D=30)
* True check_gradient_numerical(D=32)
* True check_gradient_numerical(D=64)
* True check_gradient_numerical(D=71)
Traceback (most recent call last):
  File "test.py", line 87, in <module>
    check_gradient_numerical(channels, True, True, True)
  File "test.py", line 77, in check_gradient_numerical
    gradok = gradcheck(func, (value.double(), shapes, level_start_index, sampling_locations.double(), attention_weights.double(), im2col_step))
  File "/home/long/miniconda3/envs/owdetr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 423, in gradcheck
    nondet_tol=nondet_tol)
  File "/home/long/miniconda3/envs/owdetr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 174, in get_analytical_jacobian
    jacobian_reentrant = make_jacobian(input, output.numel())
  File "/home/long/miniconda3/envs/owdetr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 31, in make_jacobian
    lambda x: x is not None, (make_jacobian(elem, num_out) for elem in input)))
  File "/home/long/miniconda3/envs/owdetr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 31, in <genexpr>
    lambda x: x is not None, (make_jacobian(elem, num_out) for elem in input)))
  File "/home/long/miniconda3/envs/owdetr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 28, in make_jacobian
    return input.new_zeros((input.nelement(), num_out), dtype=input.dtype, layout=torch.strided)
RuntimeError: CUDA out of memory. Tried to allocate 1.88 GiB (GPU 0; 3.95 GiB total capacity; 1.88 GiB already allocated; 925.62 MiB free; 1.90 GiB reserved in total by PyTorch)

Even I try the command on RTX3090 or A100, the problem is still here.
Does this problem have bad influence in training and reference ?

**Comment by akshitac8** [comment]
@kun-dragon Then it won't be a problem.

**Comment by kun-dragon** [comment]
OK, thanks a lot.
